--- 
image: 
  file: .gitpod.Dockerfile
ports: 
  - 
    onOpen: open-browser
    port: 8080
tasks: 
  - 
    command: "npm install"
    init: "pip3 install -r requirements.txt"
    name: "Test Terminal"
